// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Message struct {
	ID        uuid.UUID      `json:"id"`
	To        uuid.NullUUID  `json:"to"`
	Content   sql.NullString `json:"content"`
	Seen      sql.NullBool   `json:"seen"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID    `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
