// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListUsers(ctx context.Context, offset int32) ([]User, error)
}

var _ Querier = (*Queries)(nil)
