// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BlockSession(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteOneMessage(ctx context.Context, arg DeleteOneMessageParams) (uuid.UUID, error)
	DeleteOneUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	DeleteSession(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetMessageById(ctx context.Context, arg GetMessageByIdParams) (Message, error)
	GetSessionById(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListMessage(ctx context.Context, arg ListMessageParams) ([]Message, error)
	ListUsers(ctx context.Context, offset int32) ([]User, error)
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) (uuid.UUID, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
