// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BlockSession(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error)
	DeleteComment(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	DeleteOneMessage(ctx context.Context, arg DeleteOneMessageParams) (uuid.UUID, error)
	DeleteOneUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	DeletePost(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	DeleteSession(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	DeleteSessionByUserId(ctx context.Context, userID uuid.UUID) (uuid.UUID, error)
	GetComment(ctx context.Context, id uuid.UUID) (Comment, error)
	GetMessageById(ctx context.Context, id uuid.UUID) (Message, error)
	GetPostById(ctx context.Context, id uuid.UUID) (Post, error)
	GetSessionById(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserIdentityById(ctx context.Context, id uuid.UUID) (UserIdentity, error)
	GetUserIdentityByUserId(ctx context.Context, userID uuid.UUID) (UserIdentity, error)
	ListAllComments(ctx context.Context, postID uuid.UUID) ([]Comment, error)
	ListAllPosts(ctx context.Context, offset int32) ([]Post, error)
	ListMessage(ctx context.Context, arg ListMessageParams) ([]Message, error)
	ListUsers(ctx context.Context, offset int32) ([]User, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (uuid.UUID, error)
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) (uuid.UUID, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (uuid.UUID, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (uuid.UUID, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
